version: "3.2"
services:
  nodejs:
    # build:
    #   context: .
    image: sobirs/api-interview-app:0.1
    container_name: interview-nodejs-app
    environment:
      - MYSQL_HOST=interview-mysql-app
      - MYSQL_USER=root
      - MYSQL_PASS=root
      - MYSQL_DB=node_db
    networks:
      - frontend
      - backend
    ports:
      - "7000:7000"
  mysql:
    image: mysql:5.7
    container_name: interview-mysql-app
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=cybertek
      - MYSQL_PASSWORD=cybertek
      - MYSQL_DATABASE=node_db
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - backend
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin
    container_name: interview-phpmyadmin-app
    depends_on:
      - mysql
    environment:
      - PMA_HOST=interview-mysql-app
      - PMA_PORT= 3306
    volumes:
      - phpmyadmin:/sessions
    networks:
      - backend
    ports:
      - "7001:80"
networks:
  frontend:
  backend:
volumes:
  phpmyadmin:
  mysql:
