version: "3.2"
services:
  mysql:
    image: mysql:5.7
    container_name: interview-mysql-app
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=cybertek
      - MYSQL_PASSWORD=cybertek
      - MYSQL_DATABASE=node_db
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin
    container_name: interview-phpmyadmin-app
    depends_on:
      - mysql
    environment:
      - PMA_HOST=interview-mysql-app
      - PMA_PORT= 3306
    volumes:
      - ./phpmyadmin:/sessions
    ports:
      - "7001:80"
# volumes:
#   phpmyadmin:
#   mysql:
