version: "3.2"
services:
  mysql:
    image: mysql:5.7
    container_name: interview-mysql-app
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=cambridge
      - MYSQL_PASSWORD=cambridge
      - MYSQL_DATABASE=node_db
    volumes:
      - "./mysql:/var/lib/mysql"
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin
    container_name: interview-phpmyadmin-app
    depends_on:
      - mysql
    environment:
      - PMA_HOST=interview-mysql-app
      - PMA_PORT= 3306
    volumes:
      - "./phpmyadmin:/sessions"
    ports:
      - "7001:80"
  nodejs:
    image: sobirjon/full_stack_interview_app:0.3
    container_name: full-stack-interview-app
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=interview-mysql-app
      - MYSQL_USER=root
      - MYSQL_PASS=root
      - MYSQL_DB=node_db
      - SECRET_KEY=abc1234
      - ADMIN_EMAIL=admin@cambridge.com
      - ADMIN_PASSWORD=cambridge
      - SSL_CERT_PATH=ssl_cert_path_here
      - SSL_KEY_PATH=ssl_key_path_here
    ports:
      - "7000:7000"
